## Randomness

In [2]:
# For generating numbers.
import numpy as np

In [3]:
# Flip a coin
np.random.binomial(1, 0.5)

1

#### *Repeated Flips*

In [4]:
# Flip a fair coin 100 times.
np.random.binomial(1, 0.5, 100)

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0])

In [6]:
# number of possible outcomes
2**100

1267650600228229401496703205376

In [5]:
# Flip a coin 100 times, giving only the total number of heads.
np.random.binomial(100, 0.5)

63

#### *Twice 50/50*

In [8]:
# Keep flipping coins until we get three examples of getting five heads in ten coin tosses.

# Number of examples

N = 3

# Keep track of number of arrays generated.
total_no = 0

# Keep trying until we get three examples.
while N > 0:
    # Add 1 to total.
    total_no = total_no + 1
    # Toss 10 coins.
    tosses = np.random.binomial(1, 0.5, 10)
    # Check if we got five heads.
    if tosses.sum() == 5:
        # If we got 5 heads, print the list of heads/tails.
        print(tosses)
        # Reduce the number of examples left to find by 1.
        N = N - 1

print(f'Total generated: {total_no}')

[0 1 1 1 0 1 0 1 0 0]
[1 1 0 0 1 0 0 0 1 1]
[0 0 0 1 1 0 0 1 1 1]
Total generated: 13


#### *Counting the combinations*

In [9]:
# calculating the number of different possibilities
(10 * 9 * 8 * 7 * 6) // (5 * 4 * 3 * 2 * 1)

252

In [10]:
# Number of combinations.
no_combs = 0

# Select the first position.
for first in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
    # Select the position for the second position.
    for second in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
        # Make sure the first and second positions are different.
        if not first == second:
            # Print the combination.
            print(f'({first:2},{second:2})')
            # Add one to number of combinations.
            no_combs = no_combs + 1

# Print total number of combinations.
print(f'Total combinations is {no_combs}.')


( 1, 2)
( 1, 3)
( 1, 4)
( 1, 5)
( 1, 6)
( 1, 7)
( 1, 8)
( 1, 9)
( 1,10)
( 2, 1)
( 2, 3)
( 2, 4)
( 2, 5)
( 2, 6)
( 2, 7)
( 2, 8)
( 2, 9)
( 2,10)
( 3, 1)
( 3, 2)
( 3, 4)
( 3, 5)
( 3, 6)
( 3, 7)
( 3, 8)
( 3, 9)
( 3,10)
( 4, 1)
( 4, 2)
( 4, 3)
( 4, 5)
( 4, 6)
( 4, 7)
( 4, 8)
( 4, 9)
( 4,10)
( 5, 1)
( 5, 2)
( 5, 3)
( 5, 4)
( 5, 6)
( 5, 7)
( 5, 8)
( 5, 9)
( 5,10)
( 6, 1)
( 6, 2)
( 6, 3)
( 6, 4)
( 6, 5)
( 6, 7)
( 6, 8)
( 6, 9)
( 6,10)
( 7, 1)
( 7, 2)
( 7, 3)
( 7, 4)
( 7, 5)
( 7, 6)
( 7, 8)
( 7, 9)
( 7,10)
( 8, 1)
( 8, 2)
( 8, 3)
( 8, 4)
( 8, 5)
( 8, 6)
( 8, 7)
( 8, 9)
( 8,10)
( 9, 1)
( 9, 2)
( 9, 3)
( 9, 4)
( 9, 5)
( 9, 6)
( 9, 7)
( 9, 8)
( 9,10)
(10, 1)
(10, 2)
(10, 3)
(10, 4)
(10, 5)
(10, 6)
(10, 7)
(10, 8)
(10, 9)
Total combinations is 90.


### Exercise 1
Do the results of the following calculations, related to the aforementioned coin-toss combinations, always come out as a positive whole number? What is the formula in general? Does it always come out as a positive whole number?


In [1]:
# calculating the number of different ways of getting 5 heads
(10 * 9 * 8 * 7 * 6) / (5 * 4 * 3 * 2 * 1)

252.0

Interestingly, there is no remainder when we perform the above complex calculation.

In [2]:
# calculating the number of different ways of getting 4 heads
(10 * 9 * 8 * 7) / (4 * 3 * 2 * 1)

210.0

Again, there is no remainder when we perform the above calculation.

In [3]:
# calculating the number of different ways of getting 3 heads
(10 * 9 * 8) / (3 * 2 * 1)

120.0

In [4]:
# calculating the number of different ways of getting 2 heads
(10 * 9) / (2 * 1)

45.0

In [5]:
# and finally, calculating the number of different ways of getting 1 head
(10)/(1)

10.0

#### Conclusion: 
Each of the above calculations results in a positive whole number with no remainder.
The formula appears to be: number of desired outcomes / (divided by) remaining number of outcomes 